### ISSUE TITLE
s3-input source?

### ISSUE THREAD

**Issue by MafcoCinco** [onyx-platform/onyx-amazon-s3#3]
I found this link: https://github.com/onyx-platform/onyx-s3, though the README states that it is not under active development but would be at some point in the future (looks like it has been about 1 year).  I'm wondering if that statement is still true?  

This repo seems to be under more active development.  Will you be adding an input source to match the output source here?  Should I still use https://github.com/onyx-platform/onyx-s3 for input until such time or is there another way?  Thanks!

**Comment by MichaelDrogalis** [comment]
This repo is now the official S3 plugin, but we've kept the old one around for reference. We'll probably delete it once this repo supports input reading. We plan to implement an input plugin on this repo after the next generation streaming engine lands. We're expecting to cut an alpha release quite soon.

**Comment by lbradstreet** [comment]
We have an input plugin in the master branch, and it will be released soon
