### ISSUE TITLE
Race condition in upload

### ISSUE THREAD

**Issue by jeroenvandijk** [onyx-platform/onyx-amazon-s3#4]
The progress listener is added after the [upload has started](https://github.com/onyx-platform/onyx-amazon-s3/blob/0.9.x/src/onyx/plugin/s3_utils.clj#L36). 

This is problematic when, for instance, you are using the wrong credentials or choose the wrong bucket name. The result is that the batch will never be acked and you won't know why.

A simple solution is to call `upload` with the progress manager. The harder parter is to get to the exception and learn about the Cause. The listener [can be wrapped](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressListener.ExceptionReporter.html), but we haven't found a nice way to get the exception without calling `waitForCompletion` (blocking) on the upload.

**Comment by lbradstreet** [comment]
AWS's APIs can be pretty painful in this respect. It took me some gymnastics to get to a solution, but I'm there.

My main issue is what to do now that I can detect the exceptions properly. I am hesitant to kill the job for any failed transfers. Even issues like missing buckets could end up being transient.

How would you feel if I just reboot the peer, and let the job continue on, knowing that you will now see errors in the log as you expected?

**Comment by jeroenvandijk** [comment]
Yes we didn't see a nice solution either. Thanks for looking into this!

I'd expect that failures don't happen frequently if everything is configured/programmed properly. If we can see the error in the logs, we can do a fix and retry. If there is an issue at AWS, we cannot do much and rebooting the peer would cleanup any dirty state I suppose.

**Comment by ChrisBlom** [comment]
@lbradstreet we noticed in that in https://github.com/onyx-platform/onyx-amazon-s3/commit/fecee7a1529d4d7d37760aee63e8baa465a6cdfa#diff-e32bc006d291feb540437cd726aeb61dR48 the progress listener is still added after the upload is started, see https://github.com/onyx-platform/onyx-amazon-s3/pull/5/commits/0ddda3bac1b865f9eb90848b2e8003856d9be8e5 for a fix where the progress listener is attached when the upload is started

**Comment by lbradstreet** [comment]
Merged and released in 0.9.13.1. Note that 0.9.13.1 also includes Server Side Encryption support, in case that interests you.
